[package]
name = "jewelsd"
version.workspace = true
edition.workspace = true

[dependencies]
libjewels = { path = "../libjewels" }

env_logger = { workspace = true }
log = { workspace = true }
tokio = { workspace = true }
zbus = { workspace = true }
zbus_systemd = { workspace = true }